### ISSUE TITLE
S7G firmware 

### ISSUE THREAD

**Issue by kimwo21** [Xinyuan-LilyGO/TTGO_TWatch_Library#1]
I see you have kindly put up the firmware for the V1.6 board, but I could only buy the V1.3 board.
Do you have the firmware for V1.3 so I can restore the software if my experiments all go wrong?  Thank you.

**Comment by lewisxhe** [comment]
V13 and v16 are the same firmware, but v13 does not seem to have a swd download port. This is a bit of a hassle.

**Comment by kimwo21** [comment]
Thank you.  Very useful.

**Comment by incyi** [comment]
Will the source of the S7G fw be released ?

**Comment by incyi** [comment]
Finally, he put "something" online: https://github.com/lewisxhe/Acisp-S7xG
