### ISSUE TITLE
Is the BMA423 in TTGO-T Watch convertable to SPI mode? 

### ISSUE THREAD

**Issue by initrandom** [Xinyuan-LilyGO/TTGO_TWatch_Library#105]
Hello,

I am trying to access BMA423 data but with TTGO_TWatch_Library's BMA library there is a limitation in throughput because of I2C. 
`sensor->getAccel(accel_data);` is not fast enough for my use.

In which mode BMA423 is connected?  
Is it possible to use SPI mode in TTGO T-Watch and if is there any method or library?

**Comment by lewisxhe** [comment]
No, it only has I2C connection
