### ISSUE TITLE
Backlight Pin?

### ISSUE THREAD

**Issue by Mikumiku747** [Xinyuan-LilyGO/TTGO_TWatch_Library#11]
Hello, 

I'm trying to do control of the backlight on the T-Watch 2020, but the schematic doesn't say which pin controls the backlight, and I can't find it in the backlight code in `src/drive/tft/bl.h`. Is it Pin 12? I also see there is something about the AXP202 LDO2 in `src/TTGO.h`, do I also need to switch that on to turn the backlight on?

Thanks.

**Comment by lewisxhe** [comment]
Yes, it is connected to 12, LDO2 it is not only connected to the backlight, but also connected to the LCD driver, if you turn it off, you must re-initialize the driver again when you use it again!

**Comment by Mikumiku747** [comment]
Thank you for responding very quickly. I've been enjoying rpogramming with the W-Watch 2020.
