### ISSUE TITLE
Differentiate between hardware versions?

### ISSUE THREAD

**Issue by m-menon** [Xinyuan-LilyGO/TTGO_TWatch_Library#110]
Is there any information on how to differentiate between the different versions? For example there seems to be

> // #define LILYGO_WATCH_2020_V1             //To use T-Watch2020, please uncomment this line
> // #define LILYGO_WATCH_2020_V2             //To use T-Watch2020 V2, please uncomment this line
> // #define LILYGO_WATCH_2020_V3             //To use T-Watch2020 V3, please uncomment this line

The box does not mention anything about the version. I think one needs to look for the differences in some components to determine the difference in version. It would be good if there is some notes on this. Thanks.

**Comment by lewisxhe** [comment]
I have added the difference of each version in the README.
