### ISSUE TITLE
How to use tft_Esprite on t-watch 2020

### ISSUE THREAD

**Issue by middelbh** [Xinyuan-LilyGO/TTGO_TWatch_Library#111]
I am working on a project for my watch and need to use the tft_Esprite library from bodmer, but cannot find examples for the t-Watch 2020. Anyone?

**Comment by lewisxhe** [comment]
You can refer here: https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/examples/BasicUnit/TwatcV2Special/GPSDisplay/GPSDisplay.ino

**Comment by middelbh** [comment]
Lewis, you're great! It works as hoped! Thanks a lot!
