### ISSUE TITLE
[question] IR part on the V3 watch a sensor or transmitter

### ISSUE THREAD

**Issue by hchaudhary1** [Xinyuan-LilyGO/TTGO_TWatch_Library#113]
Is the IR part on the new "2020 V3" watch a sensor or transmitter? 940nm?

**Comment by lewisxhe** [comment]
yes, 940nm

**Comment by hchaudhary1** [comment]
Hi @lewisxhe 

Is the IR:
A. transmitter ?  
  or
B. receiver ?

Thanks you

**Comment by lewisxhe** [comment]
Transmitter
