### ISSUE TITLE
Impossible to program without battery?

### ISSUE THREAD

**Issue by v44r** [Xinyuan-LilyGO/TTGO_TWatch_Library#114]
For some reason, my T-watch only works when connected to usb since a few days ago. The battery is charged (reads 4.1V) and produces 175mA when connected to 5 100 ohm resistors in parallel... it drops to 3.55V, which seems a bit excessive for a theoretical internal resistance of <150 mohm, but should be high enough for the ESP32 to boot, right?

Anyway, the watch won't turn on unless I plug it in, and as soon as I disconnect the cable it turns off again, so the battery is doing nothing (I removed it). I want it for developing so I wouldn't mind that much... if it wasn't for the fact that I cannot upload anything without the battery. When I start uploading the watch powers off, and then an error:

```
esptool.py v3.0-dev
Serial port /dev/ttyUSB0
Connecting........_____....._____....._____....._____....._____....._____.....____An error occurred while uploading the sketch
_

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
```
This happens with any cable and any baud setting I've tried. 

I'm quite sure it's because of the battery, because a few hours ago somehow the battery worked for a while (I have no idea why) and while it lasted, I managed to upload a sketch. Now it doesn't work again, and again I cannot upload anything with the above error.

Am I wrong? Is it possible to upload a sketch just with the micro usb cable connected and no battery?

**Comment by lewisxhe** [comment]
If you encounter such a situation while booting, eliminate the problem of the USB cable and port, then what remains is that the automatic download circuit of the hardware is malfunctioning. It should be that there is no external IO0, so it cannot be downloaded manually. Please contact the supplier for after-sales processing.
