### ISSUE TITLE
source code typo in multiple places. "GPS_BANUD_RATE" instead of "GPS_BAUD_RATE".

### ISSUE THREAD

**Issue by pabloandresm** [Xinyuan-LilyGO/TTGO_TWatch_Library#12]
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/bbc438c9682f9059260a63369076e5c369dfdc9a/src/TTGO.h#L349

GPS_BANUD_RATE instead of GPS_BAUD_RATE in file TTGO.h

**Comment by lewisxhe** [comment]
thanks for your reminder
