### ISSUE TITLE
#define RTC_TIME_ZONE   How to get Mountain Standard Time? (GMT-7)

### ISSUE THREAD

**Issue by ShotokuTech** [Xinyuan-LilyGO/TTGO_TWatch_Library#121]
Hi I appreciate all the hard work on this library. I just struggle with this one thing. In LVGL SimpleWatch, what is the correct value for #define RTC_TIME_ZONE to get Mountain Standard Time? (GMT-7) Thanks!

**Comment by lewisxhe** [comment]
You can check here
https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv

**Comment by ShotokuTech** [comment]
Excellent! Thanks.
