### ISSUE TITLE
How can I restore factory firmware? 

### ISSUE THREAD

**Issue by theycallmevirgo** [Xinyuan-LilyGO/TTGO_TWatch_Library#136]
In web documentation (https://t-watch-document-en.readthedocs.io/en/latest/get-started/index.html) is specified link to download four firmware files (step 2). However, that section of the download page is blank. 

I found this page on github (https://github.com/wlcims/My-TTGO-Watch-Bin-Flash) but the filenames are different. Is it valid?

Many thanks in advance for any help

Joe

**Comment by raptyk** [comment]
Try this link: https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/master/bin

1. Download flash_download_tools
2. Download bin file v1, v2 or v3 - depending on what watch version you have
3. Run Flash tool and select downloaded file (see screenshot on link above)
