### ISSUE TITLE
Wifi constantly issues.

### ISSUE THREAD

**Issue by BararDiHoumes** [Xinyuan-LilyGO/TTGO_TWatch_Library#147]
Hello. I have some weird issues with the Wifi - not sure if it is working correctly or not in multithreading mode with 5 more threads.
Please make an example of multithreading with the Wifi, touch screen and the sound which working simultaneously please.

**Comment by LilyGO** [comment]
Please refer to this example https://github.com/sharandac/My-TTGO-Watch
