### ISSUE TITLE
preprocessor define error "-DARDUINO_T-Watch"

### ISSUE THREAD

**Issue by pabloandresm** [Xinyuan-LilyGO/TTGO_TWatch_Library#15]
When compiling anything for the board: "TTGO T-Watch", the compilation under Arduino IDE adds the following to gcc:

"-DARDUINO_T-Watch"

This is an error.

You can see that the compilation shows a warning:
"<command-line>:0:10: warning: ISO C++11 requires whitespace after the macro name"

The preprocessor defines cannot have special characters like "-".

You have to change the "-DARDUINO_T-Watch" to "-DARDUINO_TWATCH", with underscore instead, and uppercase if possible.

This is a bug, and because of a lot of luck it does not show as an error. The "-" confuses the command line into thinking it is another parameter, and not the same define.

**Comment by lewisxhe** [comment]
I made changes to espressif PR very early, but I haven't gotten their merger https://github.com/espressif/arduino-esp32/pull/4025, please change it manually. This can only be done now
