### ISSUE TITLE
'TOUCH_RST'  and was not declared in this scope

### ISSUE THREAD

**Issue by macauhome** [Xinyuan-LilyGO/TTGO_TWatch_Library#151]
when complie sample file ScreenRotation.ino show these error 
libraries\TTGO_TWatch_Library-master\src/TTGO.h:440:22: error: 'TOUCH_RST' was not declared in this scope
         digitalWrite(TOUCH_RST, LOW);
\Arduino\libraries\TTGO_TWatch_Library-master\src/TTGO.h:440:22: note: suggested alternative: 'TOUCH_INT'
         digitalWrite(TOUCH_RST, LOW);
                      ^~~~~~~~~
                      TOUCH_INT

**Comment by mike-ady** [comment]
I was able to duplicate this problem.  Make sure that 

#define LILYGO_WATCH_2019_WITH_TOUCH 

is commented out, if you are building with some other watch.
