### ISSUE TITLE
Question regarding device

### ISSUE THREAD

**Issue by tsctrl** [Xinyuan-LilyGO/TTGO_TWatch_Library#156]
@LilyGO  

1. where to contact LILYGO for technical question?
2. do ttwatch 2020 support compass? from datasheet, bma423 require additional auxiliary chip. but i not sure if that was perquisites to have the compass working with the only bma423. is the compass supported? or how to have a compass possible to work on ttwatch 2020?

thank you!

**Comment by LilyGO** [comment]
The compass needs a magnetic induction sensor, which is not equipped with twatch2020
