### ISSUE TITLE
Programmatical Way to distinguish between t-watch v1 and v3?

### ISSUE THREAD

**Issue by raomin** [Xinyuan-LilyGO/TTGO_TWatch_Library#158]
I has a couple of watches and some are v1, some are v3.
The differences between them are subtle (different GPIO for backlight, and power line for audio...)
I could off course look at the screen and change the different backlick possibility but I would like my code to determind if it's a v1 or v3 and adjust accordingly.

Is there a way for the program to identify which version the it is running on?

**Comment by LilyGO** [comment]
It is known that the V1 and V3 versions of the watch are only different from the microphone of the SPM1423HM4H. You can use this newsletter to identify if it is V3 version
