### ISSUE TITLE
question regarding touch and commit to move "touch" to private

### ISSUE THREAD

**Issue by pabloandresm** [Xinyuan-LilyGO/TTGO_TWatch_Library#16]
The commit https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/commit/98dc85961a5523e14a4ce40c0e4164317bb93a15
moved "touch" to private inside TTGO class.

I have a T-Watch 2019 with display and touch.

I was initializing my code doing "ttgo->touch->enterSleepMode();" to reduce power consumption, as I was not using the touch screen.

But I cannot do it anymore.

In the code you can do ttgo->displayOff() that executes "touch->enterSleepMode()", but also turns off the display.

If I want to keep the display ON, but still do "touch->enterSleepMode()", I cannot do it anymore, because touch is now private.

How can I do this? is this a bug?

**Comment by lewisxhe** [comment]
There have been a lot of changes recently, some may be ignored, I will add a touch sleep method
