### ISSUE TITLE
Cannot upload example sketch

### ISSUE THREAD

**Issue by spleenware** [Xinyuan-LilyGO/TTGO_TWatch_Library#160]
Just got my 2020 V3 watch, and trying the LGVL_Button sample sketch.

Getting this error when uploading:

esptool.py v3.1
Serial port /dev/cu.usbmodem53190043851
Connecting.....
Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 08:3a:f2:66:5b:18
Uploading stub...

A fatal error occurred: Failed to write to target RAM (result was 01070000)
A fatal error occurred: Failed to write to target RAM (result was 01070000)

**Comment by LilyGO** [comment]
Do you have the same error when uploading other routines? 
If so, it is possible that the RAM is damaged.
If it is not hardware damage, please try to use ESP32TOOLS to clear all chip information and upload again.
