### ISSUE TITLE
TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'bool TFT_eSPI::initDMA()':

### ISSUE THREAD

**Issue by RubensZimbres** [Xinyuan-LilyGO/TTGO_TWatch_Library#173]
Hi, I have a 2020-V3  Watch and I just installed TTGO-Watch library but I am unable to compile and upload due to the following error:

`
/home/tone/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'bool TFT_eSPI::initDMA()':
/home/tone/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp:1103:5: sorry, unimplemented: non-trivial designated initializers not supported
     };
     ^
/home/one/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp:1103:5: sorry, unimplemented: non-trivial designated initializers not supported
/home/one/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp:1103:5: sorry, unimplemented: non-trivial designated initializers not supported
/home/one/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp:1103:5: sorry, unimplemented: non-trivial designated initializers not supported
/home/one/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp:1103:5: sorry, unimplemented: non-trivial designated initializers not supported
/home/one/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp:1103:5: sorry, unimplemented: non-trivial designated initializers not supported
/home/one/Arduino/libraries/TTGO_TWatch_Library-master/src/libraries/TFT_eSPI/TFT_eSPI.cpp:1103:5: sorry, unimplemented: non-trivial designated initializers not supported
exit status 1
Error compiling for board TTGO T-Watch.
`

It looks like this is related to display, the TFT_eSPI.cpp file, it is a recurrent error in all examples I try, /dev/tty/ACM0 is enable and accessible, and I followed the installation instructions.

Any ideas on what can be done ?

I am on Ubuntu

Thanks in advance

**Comment by lewisxhe** [comment]
Please try cloning the repository again
