### ISSUE TITLE
Unable to upload any example of the library

### ISSUE THREAD

**Issue by Kaki-In** [Xinyuan-LilyGO/TTGO_TWatch_Library#174]
Hi, 
I can upload a program to my watch, and this one works successfully : 
 
``` cpp
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);

}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.printf("Test\n");
  delay(1000);
}
```

But, when I try to upload a TTGO_TWatch_Library example program, it is not uploaded to the card :
 - While the compilation prcess, I have few cpp errors.
 - At the end of the compilation, it blocks after saying which libraries are used for something as one minute and then says "Error : connection has been disposed".
 - Immediatly before and after this message, the card is still available.

I have set the #define LILYGO_WATCH_2020_V3 at the begginning of the config.h file and just installed the latest versions of the ESP32 cards json file and of the LILYGO_WATCH library. 

Can someone help me?

**Comment by lewisxhe** [comment]
Please provide a screenshot

**Comment by Kaki-In** [comment]
[There](https://www.flopcreation.fr/VideoGithubTTGOWatchIssue.mp4) is the video capture of what I get.

**Comment by Kaki-In** [comment]
I did a simple syntax check on an errored message and got the same result : it seems that it itsn't about the watch, but the library itself.

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/193537286-753b0ce9-a938-4fe6-8684-c2add98c2756.png)

It's normal on windows, I think this may have something to do with the version of arduino-esp32, what version of core are you using?

**Comment by Kaki-In** [comment]
I actually am on Ubuntu

**Comment by Kaki-In** [comment]
cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/194791660-2ecb5c15-3bf7-4a98-a1d3-74cbdcbf3470.png)

I tried in the newly installed UBuntu22.04.1 LTS and found no errors

**Comment by lewisxhe** [comment]
This is a video recorder
https://youtu.be/BzbEkUnE7C4

**Comment by Kaki-In** [comment]
Go into File -> Preferences
In the "Compiler Warning" Section, select "All"

Retry to compile

Installing a second version I had a lot of same errors...

**Comment by Kaki-In** [comment]
![image](https://user-images.githubusercontent.com/91763754/204157096-78d620db-0579-42ea-8cb8-71e0569b418f.png)

**Comment by Kaki-In** [comment]
( a second version of ubuntu, I am using a vm)

**Comment by Kaki-In** [comment]
Ok I just disactived this and now it works!

Thanks for your help

**Comment by Kaki-In** [comment]
Just a little question quickly... Where is the main Operating System of the watch?

**Comment by lewisxhe** [comment]
If you have any questions, please restart
