### ISSUE TITLE
Version 1.2.0 tag missing

### ISSUE THREAD

**Issue by red-fox-star** [Xinyuan-LilyGO/TTGO_TWatch_Library#18]
The library.json file shows the version should be 1.2.0, but currently the only tag available on this repository is 1.1.0. It makes it hard to see what code I'm running against when I can't read the library code for the published version.

https://raw.githubusercontent.com/Xinyuan-LilyGO/TTGO_TWatch_Library/master/library.json

**Comment by lewisxhe** [comment]
Just updated, it will take some time
