### ISSUE TITLE
Any tips about how to use images ?

### ISSUE THREAD

**Issue by DarkMulet** [Xinyuan-LilyGO/TTGO_TWatch_Library#183]
Hello there it's me again, I started to understand how the watch workw because studying it non stop for the last few days
I want now to show images on the watch but I have two problems here:
I only found examples using lvgl to show images.

First : is there a way to load images in sprites instead of lvgl ? It would draw must faster and easier to use with sprites I think.

Second : The only working converter from images to c I've found is the official lvgl converter but it only convert to Hex2 so no colors are availables in the images because colors are encoded in Hex4 on the watch, so  how can I show colorfull images ?

The purpose here is to start making Applications Icons like Apple Watch, obviously using colors.

Thank you in advance.

**Comment by lewisxhe** [comment]
see there https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/master/examples/TFT_eSPI/Sprite/Sprite_image_8bit

ImageConverter  : http://rinkydinkelectronics.com/t_imageconverter565.php

**Comment by lewisxhe** [comment]
If there is a problem, please reopen it
