### ISSUE TITLE
TWatch V2 'MOTOR_PIN' was not declared in this scope

### ISSUE THREAD

**Issue by spilz87** [Xinyuan-LilyGO/TTGO_TWatch_Library#192]
Hello,

I'm trying to use the motor on my TWatch V2, but I don't find how to use it :(
I tried to add 
`#define LILYGO_WATCH_HAS_MOTOR   //Use Motor module`
but I got 
`'MOTOR_PIN' was not declared in this scope`

someone know how to use the motor on the TWatch V2 ?

thanks in advance :)

Spilz

**Comment by lewisxhe** [comment]
See [this](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/master/examples/BasicUnit/TwatcV2Special/DRV2605_Basic)
