### ISSUE TITLE
TWatch-S3 Radio example Scan spectrum and scan spectrum (frequency) fails on error -20 (invalid modem)

### ISSUE THREAD

**Issue by mistrjirka** [Xinyuan-LilyGO/TTGO_TWatch_Library#199]
Hi I have the TWatch-S3 with LoRa 433mhz. The LoRa works fine in the factory example but when trying the scan spectrum examples, it always fails with this message: 
"[SX1262] Uploading patch ... success!
[SX1262] Setting scan parameters ... failed, code -20
"
Does anyone have the same issue?

**Comment by lewisxhe** [comment]
Completed the repair, the example comes from RadioLib
