### ISSUE TITLE
RTC not remembering time after synchronization TTGO T-Watch S3

### ISSUE THREAD

**Issue by mistrjirka** [Xinyuan-LilyGO/TTGO_TWatch_Library#200]
I have the TTGO T-Watch S3 and I have an issue of time being kept while the watch is off. 
What I did:
Uploaded the examples/peripheral/RTC_TimeSynchronization -> this worked I have the correct time
Uploaded the examples/peripheral/RTC_TimeLib -> this also worked but now I have the time that was during the synchronization (the RTC didn't keep the correct time during the upload now the watch is a bit behind)
After rebooting the watch loads the old time (the time of the synchronization). 

My wild theory is that the battery of the RTC is dead/disconnected so it saves time for the synchronization and when the watch is rebooted it loses power it loads the time when it was last synchronized.

What are my options?

**Comment by lewisxhe** [comment]
Sorry, because the RTC charging voltage is not set, the RTC battery cannot be charged, it has been fixed.

https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/commits/t-watch-s3
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/commit/27e64b8323709502f30d81fc7f45b156e1000730

**Comment by lewisxhe** [comment]
The first time you need to charge the RTC continuously for about 30 minutes, the backup battery will be charged to a normal level, and it can last for a period of time after power off.

**Comment by mistrjirka** [comment]
Thank you for quick response and hopefully fix. I will compile the new version and report back.

**Comment by lewisxhe** [comment]
1. I updated the T-Watch dependency library [SensorLib](https://github.com/Xinyuan-LilyGO/T-Watch-Deps), please update
2. 
3. I updated the example, please pull it again and test it.

Reason: If the backup battery is completely dead, the initialization of the RTC will fail and the time cannot be obtained.

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/assets/22990954/153e05b6-ed83-410e-bbe7-58b1dfcfb684)

If it still doesn't work, if you have a multimeter, please check whether the voltage of these two points is normal.

**Comment by mistrjirka** [comment]
> 1. I updated the T-Watch dependency library [SensorLib](https://github.com/Xinyuan-LilyGO/T-Watch-Deps), please update
> 3. I updated the example, please pull it again and test it.
> 
> Reason: If the backup battery is completely dead, the initialization of the RTC will fail and the time cannot be obtained.

Thanks I will try that. In the worst case scenario where the battery is completely dead. How hard is it to replace the battery? is is possible with ts100? Or should I rather contact customer support?

**Comment by mistrjirka** [comment]
> 1. I updated the T-Watch dependency library [SensorLib](https://github.com/Xinyuan-LilyGO/T-Watch-Deps), please update
> 
>     3. I updated the example, please pull it again and test it.
> 
> 
> Reason: If the backup battery is completely dead, the initialization of the RTC will fail and the time cannot be obtained.

I am really happy to report that the new code works! Thank you so much for the amazing support and quick updates.
