### ISSUE TITLE
Cannot build file Platformio 

### ISSUE THREAD

**Issue by Schjonning** [Xinyuan-LilyGO/TTGO_TWatch_Library#211]
When trying to build in platformio i get following 
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\twatch-s3\firmware.elf] Error 1

![Unavngivet](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/assets/121898310/cd59d222-8c73-4019-a31f-158a1b1d4c90)

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/assets/22990954/7c35b3b1-f15d-408a-aefb-32ea78a826df)

src_dir must select an example for compilation
