### ISSUE TITLE
Where is config.h?

### ISSUE THREAD

**Issue by ShotokuTech** [Xinyuan-LilyGO/TTGO_TWatch_Library#22]
Sorry to ask a noob question. But readme mentions config.h for selection of watch type. I download the zip and go through the Arduino TTGO_TWatch_Library-master folder. I cannot find config.h. Thanks in advance.

**Comment by lewisxhe** [comment]
In every example there is a config.h

**Comment by ShotokuTech** [comment]
Interesting. This morning, nothing showed up when I did the search. Must be some latency in the OneDrive sync. Thank you.
![image](https://user-images.githubusercontent.com/65474147/86679233-3e634b00-bfb2-11ea-8eb4-dfccbb79de6b.png)
