### ISSUE TITLE
T-Watch S3 Write timeout

### ISSUE THREAD

**Issue by SQ2CPA** [Xinyuan-LilyGO/TTGO_TWatch_Library#229]
Hello. I have 6 pcs of T-Watch S3. 
Half of them works fine but other half cannot be flashed, I got error: Write timeout

![Code_WvgpyhzfFr](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/assets/155308374/fa4988d5-f930-400b-bd02-0de3262dac78)

**Comment by jeff-burright** [comment]
I had this problem recently. To solve it, first I did the trick with the button under the battery as described in the Readme file, then I used the esp flash tool from espressif to clear the flash on the watch. After that, I was able to connect and upload. Might be worth a try for you.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/t-watch-s3/firmware#note
