### ISSUE TITLE
Update for twatch 2020

### ISSUE THREAD

**Issue by jhfoo** [Xinyuan-LilyGO/TTGO_TWatch_Library#23]
Can the author update data for their latest watch model?

If the hardware, pin map for 2020 is exactly the same as previous models, please confirm in your README.MD. I don't think it's exactly the same, and am not sure where and how are they different.

**Comment by lewisxhe** [comment]
2020 is not added in the README, but you can view the definition here 

https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/src/board/twatch2020_v1.h
