### ISSUE TITLE
Which GPIO pin is connected to the physical knob on the side of the lilygo T-Watch S3?

### ISSUE THREAD

**Issue by alexflint** [Xinyuan-LilyGO/TTGO_TWatch_Library#232]
On the LilyGo T-Watch S3 2020, which GPIO pin is connected to the physical knob on the side of the watch?

I'm aware of the schematic [here](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/t-watch-s3/schematic/T_WATCH_S3.pdf) but I can't find the knob in that schematic. 

I have also looked through the pin definitions in C code [here](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/t-watch-s3/src/utilities.h#L116-L163) but I see no mention of the physical knob.

The knob I'm referring to is this one:

![Untitled-2024-03-03-1126](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/assets/640247/9ce96241-b310-466e-a18f-415c920ae71b)

**Comment by lewisxhe** [comment]
This is not a knob, this is the on/off button from power management
