### ISSUE TITLE
Boot Text Cannot be changed

### ISSUE THREAD

**Issue by ThBean** [Xinyuan-LilyGO/TTGO_TWatch_Library#237]
Affected Device: Lilygo TTGO watch S3
I am using [this repository ](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/t-watch-s3)
On boot the device can only display "Hello T-Watch" this cannot be changed through Arduino IDE since I can't find the code that refers too it. Ideally i could remove or customize this text.

**Comment by jeff-burright** [comment]
You should be able to find it in LilyGoLib.cpp around line 119. Search for "drawstring"

**Comment by ThBean** [comment]
Thanks this solves the issue,
for anyone else viewing this here is the Location path:
`~Arduino/libraries/TTGO_TWatch_Library/src/LilyGoLib.cpp`
