### ISSUE TITLE
Question: Access to GPIO for external buttons on T-Watch-S3

### ISSUE THREAD

**Issue by hcr-mit** [Xinyuan-LilyGO/TTGO_TWatch_Library#250]
I am evaluating this watch for use in a different case where there will be three momentary buttons. Is there a way to access any GPIO connections in this watch design?

Touch screen manipulation of the applications, is not an option due to the nature of how the user can interact.

Please, reply soon. Thank you.

**Comment by lewisxhe** [comment]
The FPC cable interface is reserved internally, and there is no external GPIO for connection

**Comment by hcr-mit** [comment]
I am closing this discussion
