### ISSUE TITLE
Is it possible to receive ASK modulated message over 433 MHz?

### ISSUE THREAD

**Issue by sguerrini97** [Xinyuan-LilyGO/TTGO_TWatch_Library#253]
Hello,

we are planning to buy some T-Watch S3 and we would like to pair them with "call buttons".

The buttons we already have are these and they basically send an ID over 433 MHz using ASK modulation:
![image](https://github.com/user-attachments/assets/1d5d72b4-0743-4b33-b6d2-43b627c0e093)

We also own a T-Watch S3, 433 MHz version (K217) for our tests.
We are trying to receive the message from the buttons on our T-Watch S3 but to no avail, is this an SX1262 limitation or is this a software limitation? We tried some of the samples but none of them seems to match our setup.

If this is an hardware limitation, may I ask if any of the previous watches versions support the ASK modulation?

Thank you
Kind regards

**Comment by lewisxhe** [comment]
SX1262 does not support ASK
![image](https://github.com/user-attachments/assets/c6aa7917-d3b2-447b-be4d-a976a0eab126)

**Comment by sguerrini97** [comment]
I see, thank you very much :)
