### ISSUE TITLE
T-Watch 2020 wont charge batttery

### ISSUE THREAD

**Issue by bloutix** [Xinyuan-LilyGO/TTGO_TWatch_Library#26]
Hi,

after many test mm ttwatch 2020 battery won't charge?

How to fix that?

thanks

**Comment by lewisxhe** [comment]
Do you get charging current?  How do you judge it cannot be charged?

**Comment by bloutix** [comment]
I have tried AXP20x samples and battery voltage is around 2.9V and vbus is around 120mA.
I have tried to set charge current between 300 and 1000mA with no success.
I have tried on usb port, on usb wall charger, i replaced the battery. All without succes.
The battery percentage stay at 0% .


________________________________
De : lewis he <notifications@github.com>
Envoyé : mercredi 8 juillet 2020 16:23
À : Xinyuan-LilyGO/TTGO_TWatch_Library <TTGO_TWatch_Library@noreply.github.com>
Cc : Bloutix <bloutix@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [Xinyuan-LilyGO/TTGO_TWatch_Library] T-Watch 2020 wont charge batttery (#26)


Do you get charging current? How do you judge it cannot be charged?

**Comment by lewisxhe** [comment]
@bloutix Please run the AXP202 monitoring example, you can see whether it is normal, if not, please contact customer service

https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/examples/BasicUnit/AXP20x_ADC/AXP20x_ADC.ino

**Comment by bloutix** [comment]
The monitoring example display this values:
Vbus: 5057.50mV
Vbus: stay beetwen 75mA and 131.62mA
BATT: 2960.10mV
Per: 0%

**Comment by lewisxhe** [comment]
Can you tell me the complete display? Or give me a photo

**Comment by bloutix** [comment]
[cid:12150f3d-acf1-47f4-8060-bb5933b360b4]
________________________________
De : lewis he <notifications@github.com>
Envoyé : vendredi 10 juillet 2020 15:27
À : Xinyuan-LilyGO/TTGO_TWatch_Library <TTGO_TWatch_Library@noreply.github.com>
Cc : Bloutix <bloutix@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Xinyuan-LilyGO/TTGO_TWatch_Library] T-Watch 2020 wont charge batttery (#26)


Can you tell me the complete display? Or give me a photo

**Comment by bloutix** [comment]
________________________________
De : lewis he <notifications@github.com>
Envoyé : vendredi 10 juillet 2020 15:27
À : Xinyuan-LilyGO/TTGO_TWatch_Library <TTGO_TWatch_Library@noreply.github.com>
Cc : Bloutix <bloutix@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Xinyuan-LilyGO/TTGO_TWatch_Library] T-Watch 2020 wont charge batttery (#26)


Can you tell me the complete display? Or give me a photo

**Comment by lewisxhe** [comment]
Please update the warehouse to the latest, it contains more detailed information

**Comment by bloutix** [comment]
________________________________
De : lewis he <notifications@github.com>
Envoyé : vendredi 10 juillet 2020 15:54
À : Xinyuan-LilyGO/TTGO_TWatch_Library <TTGO_TWatch_Library@noreply.github.com>
Cc : Bloutix <bloutix@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Xinyuan-LilyGO/TTGO_TWatch_Library] T-Watch 2020 wont charge batttery (#26)


Please update the warehouse to the latest, it contains more detailed information

**Comment by bloutix** [comment]
![IMG_20200710_160042](https://user-images.githubusercontent.com/35742/87162858-c99c5380-c2c6-11ea-806d-cdf73d4ed00e.jpg)

**Comment by lewisxhe** [comment]
It looks like the battery is connected. You can unplug the USB, leave the battery in a discharged state, then wait for tens of minutes to let the power drain, and then plug in the USB again to check its charging current

**Comment by bloutix** [comment]
With the original battery charge is at 0.00mA and the bat voltage decrease slowly (around 2800mV),
with another battery charge is 0mA or sometime it's at 2mA with a bat volatge around 3270mV

**Comment by lewisxhe** [comment]
It seems that the charging part may be damaged, please contact LilyGO sales, this can not be repaired by the software.
