### ISSUE TITLE
T-watch 2020v1 schematics details

### ISSUE THREAD

**Issue by sdrabb** [Xinyuan-LilyGO/TTGO_TWatch_Library#27]
Please provide us T-watch 2020 v1 esp32 pinout connection details.

**Comment by lewisxhe** [comment]
LilyGo does not provide the schematic diagram of TWatch, all IO Pins are defined in the file

https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/src/board/twatch2020_v1.h

**Comment by NilsBe** [comment]
I understand that schematics are not published.
Would it be possible though to give some details about the connected pins of the AXP202?

I would love to understand this a little better:

    // Turn off unused power
    ttgo->power->setPowerOutPut(AXP202_EXTEN, AXP202_OFF);
    ttgo->power->setPowerOutPut(AXP202_DCDC2, AXP202_OFF);
    ttgo->power->setPowerOutPut(AXP202_LDO3, AXP202_OFF);
    ttgo->power->setPowerOutPut(AXP202_LDO4, AXP202_OFF);

And what about: 

AXP202_EXTEN
AXP202_DCDC3
AXP202_LDO2
AXP202_LDO4
AXP202_DCDC2
AXP202_LDO3

**Comment by stackshadow** [comment]
Found it in the docs. See here:
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/docs/pinmap.md#3-axp202-power-management-channel

**Comment by tuupola** [comment]
@stackshadow There are some gotchas such as just enabling `LDO2` is not enough. You also need to enable PWM on `GPIO12`. I do not really understand why. Still work in progress but I am documenting my findings at:

https://github.com/tuupola/esp_twatch2020

**Comment by drunkscientist** [comment]
> LilyGo does not provide the schematic diagram of TWatch, all IO Pins are defined in the file
> 

pin numbers are NOT a substitute for a schematic or wiring diagram, it would be helpful if they were released
@tuupola do you happen to know if the unused LDO4/LDO5 are enabled in software? like if i take some tiny wire and tiny soldering iron with a microscope, will a program calling them work or throw an error?

**Comment by lewisxhe** [comment]
LDO4,5 are not used in V1.

**Comment by destroyedlolo** [comment]
Hello,

TTGO kindly provided the schema and I published it on my website with their agreement :
http://destroyedlolo.info/ESP/Tech%20TWatch/

I got the same for the LilyPI but didn't plushed it.

Bye

Laurent

**Comment by drunkscientist** [comment]
@destroyedlolo this is AWESOME THANK YOU

**Comment by X-Ryl669** [comment]
@destroyedlolo Can you also publish the LilyPI schematic too ?

**Comment by lashansen** [comment]
> Hello,
> 
> TTGO kindly provided the schema and I published it on my website with their agreement : http://destroyedlolo.info/ESP/Tech%20TWatch/
> 
> I got the same for the LilyPI but didn't plushed it.
> 
> Bye
> 
> Laurent

Hi Laurent, Link is not working anymore. Any chance you can share the schematic of the TTGO T-Watch 2020v1 again?
It would really make my day :)
Br Lasse

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/master/Schematic
