### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by PhilColbert** [Xinyuan-LilyGO/TTGO_TWatch_Library#3]
Trying to compile all this code runs into many errors, does anyone have a version that compiles?

thanks

**Comment by PhilColbert** [comment]
Compiles on arduino but not as a component for espidf.... probably compilation flags :)

**Comment by incyi** [comment]
Please tell me when you can compile it for esp-idf.

**Comment by salem83** [comment]
@PhilColbert How did you manage to get it compiled?
i just installed Arduino 1.8.12 and ESP 1.0.4

which gives me the following errors:

`
In file included from C:\Users\Administrator\Documents\Arduino\libraries\TTGO_TWatch_Library\src\MPR121.h:5:0,

                 from C:\Users\Administrator\Documents\Arduino\libraries\TTGO_TWatch_Library\src\MPR121.cpp:29:

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'uint8_t MPR121_Class::readRegister8(uint8_t)':

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:99:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)

     uint8_t requestFrom(int address, int size);

             ^

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:97:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)

     uint8_t requestFrom(uint8_t address, uint8_t size);

             ^

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'uint16_t MPR121_Class::readRegister16(uint8_t)':

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:99:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)

     uint8_t requestFrom(int address, int size);

             ^

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:97:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)

     uint8_t requestFrom(uint8_t address, uint8_t size);

             ^

In file included from C:\Users\Administrator\Documents\Arduino\libraries\TTGO_TWatch_Library\src\BBQ10Keyboard.h:3:0,

                 from C:\Users\Administrator\Documents\Arduino\libraries\TTGO_TWatch_Library\src\BBQ10Keyboard.cpp:5:

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'uint8_t BBQ10Keyboard::readRegister8(uint8_t) const':

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:99:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)

     uint8_t requestFrom(int address, int size);

             ^

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:97:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)

     uint8_t requestFrom(uint8_t address, uint8_t size);

             ^

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h: In member function 'uint16_t BBQ10Keyboard::readRegister16(uint8_t) const':

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:99:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)

     uint8_t requestFrom(int address, int size);

             ^

C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\Wire\src/Wire.h:97:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)

     uint8_t requestFrom(uint8_t address, uint8_t size);

             ^

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chrtbl_f72+0x0): multiple definition of `chrtbl_f72'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chrtbl_f72+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_20+0x0): multiple definition of `chr_f72_20'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_20+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_2D+0x0): multiple definition of `chr_f72_2D'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_2D+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_2E+0x0): multiple definition of `chr_f72_2E'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_2E+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_30+0x0): multiple definition of `chr_f72_30'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_30+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_31+0x0): multiple definition of `chr_f72_31'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_31+0x0): first defined here

c:/users/administrator/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-80-g6c4433a-5.2.0/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: Warning: size of symbol `chr_f72_31' changed from 159 in libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o to 158 in libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_32+0x0): multiple definition of `chr_f72_32'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_32+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_33+0x0): multiple definition of `chr_f72_33'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_33+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_34+0x0): multiple definition of `chr_f72_34'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_34+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_35+0x0): multiple definition of `chr_f72_35'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_35+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_36+0x0): multiple definition of `chr_f72_36'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_36+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_37+0x0): multiple definition of `chr_f72_37'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_37+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_38+0x0): multiple definition of `chr_f72_38'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_38+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_39+0x0): multiple definition of `chr_f72_39'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_39+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.chr_f72_3A+0x0): multiple definition of `chr_f72_3A'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.chr_f72_3A+0x0): first defined here

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72x53rle.c.o:(.rodata.widtbl_f72+0x0): multiple definition of `widtbl_f72'

libraries\TTGO_TWatch_Library\TFT_eSPI\Fonts\Font72rle.c.o:(.rodata.widtbl_f72+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

Multiple libraries were found for "SD.h"
 Used: C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
exit status 1
Error compiling for board TTGO T-Watch.
`

**Comment by lewisxhe** [comment]
This is my mistake, I upgraded TFTeSPI, I only tested in platformIO, it will indeed cause an error in Arduino, I will roll back the code first, you can pull it again @salem83

**Comment by salem83** [comment]
@lewisxhe thanks. unfortunately, I still got the same errors in the Arduino IDE. 
But i preferrably work in PlatformIO where i ahve no problems.

**Comment by Fusseldieb** [comment]
Hijacking this thread to post my solution about the compilation errors I had and struggled for days!
My error was that something was wrong with the Ticker library, but yours could differ.

The solution is, at least if you're using PlatformIO, to **uninstall every library available in the "Global Storage"**, mine had a library there called Ticker, which WASN'T the same as this library used, and thus gave errors.

![image](https://user-images.githubusercontent.com/4715129/105521900-4dde8300-5cbb-11eb-9dac-6f69405fe165.png)

Then install the libraries needed for your Project one by one and be sure to select your active TTGO project when installing those! See below:
![image](https://user-images.githubusercontent.com/4715129/105522134-9eee7700-5cbb-11eb-962a-31f34c61a3d5.png)

And now try to compile again. Should now work!
