### ISSUE TITLE
Is it possible to wake up the TWatch 2020 from deep sleep by pressing the button?

### ISSUE THREAD

**Issue by NilsBe** [Xinyuan-LilyGO/TTGO_TWatch_Library#30]
Everything already in the title. 

I checked and uploaded the deep sleep sketch. 
It's great and it might be necessary to use the deep sleep mode for a reasonable battery run time. 

But IMHO the deep sleep makes only sense if one can wake it up by pressing the button.

As schematics are not available I would be really greateful an example sketch for such a solution.

Thanks a lot.
Nils

**Comment by xaksh** [comment]
Following this.. would be really helpful to get insight

**Comment by sdrabb** [comment]
Deep sleep cause esp32 reboot, i think is a bit reasonable esp32 light_sleep

**Comment by lewisxhe** [comment]
Most of them are early examples, and there is no adaptation for 2020.I will update the deep sleep example on Monday.

**Comment by NilsBe** [comment]
Fantastic! Great work Lewis.
Thanks.
