### ISSUE TITLE
Backlight dims when calling shake()

### ISSUE THREAD

**Issue by sweetlilmre** [Xinyuan-LilyGO/TTGO_TWatch_Library#35]
After calling the shake() function the backlight dims.
Seems to be similar to #9 is there a way to reset the backlight brightness after using the motor?
To reproduce, replace the function setting_event_cb() in gui.cpp in the SimpleWatch example with

```
static void setting_event_cb()
{
  TTGOClass *ttgo = TTGOClass::getWatch();
  ttgo->motor_begin();
  ttgo->shake();
  menuBars.hidden(false);
}
```

**Comment by lewisxhe** [comment]
Does the backlight dim after shake? It should recover after shaking.

**Comment by sweetlilmre** [comment]
Hi, it dims immediately after shake and does not recover.

**Comment by lewisxhe** [comment]
I will check if I have time! I will record this question and the question will be closed!

**Comment by sweetlilmre** [comment]
Thank you, I appreciate it. I will also look when I have time

**Comment by billyischilly** [comment]
Hi! Was this ever fixed or does anyone know how to manually reset the screen brightness after it dims? I'm still using an older release of the library (1.2) with the V1 watch and can't seem to get full brightness. back except by rebooting.

**Comment by sweetlilmre** [comment]
It doesn't look like it and development seems to have stalled here.

The motor seems to be directly controlled via IO (https://github.com/destroyedlolo/TTGO_TWatch_Library/blob/master/docs/watch_2020_v1.md). I'm assuming that there is some kind of direct IO write that is interferring with another peripheral (most likely the AXP202) although there could be something else completely out of band happening. If I ever get the time to look at this again, I'll attempt to find a solution.

**Comment by sweetlilmre** [comment]
Excellent! If possible, would you submit a pull request to this repo and mention in a following comment so that others can see this solution?

**Comment by billyischilly** [comment]
Sure! Hope I've done this right - only my second ever pull request!

#146

**Comment by sweetlilmre** [comment]
Looks good to me. I assume you changed the chanel to 4 so that backlight is 0, buzzer 2 and motor 4, giving a channel separation for each function?

@lewisxhe could you please take a look at this?

**Comment by billyischilly** [comment]
Yeah, haven't tested anything with the buzzer yet but realised I might have created more problems on channel 3. All seems to still be working fine so far!
