### ISSUE TITLE
USB-C to USB-C cable not working

### ISSUE THREAD

**Issue by incyi** [Xinyuan-LilyGO/TTGO_TWatch_Library#4]
When I connect my T-Watch with an USB-C to USB-C cable on my MacBook Pro 2018, it does not work. But when I connect an USB-C to USB-A adapter in my MacBook. And use an USB-A to USB-C cable, it works. I already tried different USB-C cables.

Is this a hardware or software issue ?

**Comment by lewisxhe** [comment]
If there is a hardware problem, then you should not have A-> C, so I think this is a Mac problem! I use macbook air A-> C and it works fine

**Comment by incyi** [comment]
I'll try another laptop with USB-C.

**Comment by incyi** [comment]
Apple is stupid, it’s really only on the mac not working.

**Comment by incyi** [comment]
Oke, this is getting really strange. I found some cables, which get it working on the mac. I think this is an USB-C cable issue.
