### ISSUE TITLE
Using two I2C buses

### ISSUE THREAD

**Issue by glfurtado61** [Xinyuan-LilyGO/TTGO_TWatch_Library#5]
Hi. I'm using GPIO25 and GPIO26 (on expansion connector) to comunicate by I2C. I have suceeded but touching the screen was out. I'm using Wire1 on extension communication, on IDE Arduino. What can I do to solve this issue?

**Comment by lewisxhe** [comment]
Wire1 is already used in touch screen, if you need to use 25,26, then you can only use softI2C

**Comment by glfurtado61** [comment]
OK, Lewis He. Thank you for your reply.
Can you suggest a library that´s ok for use with T-Watch? Some in special?
Thanks in advance
Gustavo

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sáb., 28 de mar. de 2020 às 21:53, lewis he <notifications@github.com>
escreveu:

**Comment by lewisxhe** [comment]
You can use https://github.com/pasko-zh/brzo_i2c

**Comment by glfurtado61** [comment]
OK, thanks. I'll try that!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em dom., 29 de mar. de 2020 às 12:04, lewis he <notifications@github.com>
escreveu:
