### ISSUE TITLE
Why not usw syncToRtc instead ?

### ISSUE THREAD

**Issue by Altron-2k20** [Xinyuan-LilyGO/TTGO_TWatch_Library#51]
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/dca8fbee0b6438b94d2c20d4d54325f56fc7b987/examples/LVGL/SimpleWatch/gui.cpp#L1183

It would reduce the back and forth as the SNTP response will already update the system time. With syncToRtc will save directly the current system time to RTC.

**Comment by lewisxhe** [comment]
There is no why. This is an example written when I first started doing T-Watch, and it is not maintained, just for reference.
