### ISSUE TITLE
Lora sample don't work

### ISSUE THREAD

**Issue by georaura** [Xinyuan-LilyGO/TTGO_TWatch_Library#6]
HI, 
I am trying to compile the lora example using the arduino-LoRa library, the program compiles without errors, but stops when initializing the lora module.
Specifically it stops at the following code block:

--------------
int ret = 0; 
do {
        lv_task_handler();
        ret = LoRa.begin(BAND);
        delay(500);
    } while (!ret);
----------------
Any suggestion?

**Comment by lewisxhe** [comment]
If you run the sample program and cannot initialize normally, the first step is to exclude whether the FPC cable connection is normal, and then consider whether there is a hardware problem with the lora board.

**Comment by lewisxhe** [comment]
You also need to determine whether the frequency accepted by the module is used, defined in line 24 in lora.ino

**Comment by georaura** [comment]
I define the frequency in line 24 in lora.ino at 915 (#define LORA PERIOD 915), by the result is the same: the program compiles without errors, but stops with "**Begin Lora Module**" message.  
With the st7xg lora example I have not any problem, then I think Isn't a hardware problem with the lora board.

**Comment by lewisxhe** [comment]
Oh, are you using S76G? Then you can't run this /examples/lora/lora.ino, this is for another board

**Comment by georaura** [comment]
Yes, I'm using S76G. Then isn't possible use arduino-LoRa library  with this board?

**Comment by lewisxhe** [comment]
S76G has built-in firmware, so it can't be used.
