### ISSUE TITLE
Is there code to set an alarm on the watch?  Thinking it could be added to the apps in the current firmware.

### ISSUE THREAD

**Issue by jvermill-zz** [Xinyuan-LilyGO/TTGO_TWatch_Library#60]
Would like to be able to set an alarm or a timer on the watch.  Ideally would like option for motor vibration as alert or audible.

**Comment by jvermill-zz** [comment]
Found this but unsure how I'd massage this into the example app space in the My-TTGO-Watch code: https://github.com/lixy123/TTGO_T_Watch_Alarm_Clock

**Comment by lewisxhe** [comment]
This example is based on 2019 and can also be run in 2020
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/master/examples/Shield/AlarmClock
