### ISSUE TITLE
Is there an example for BLE connectivity to Android phone?

### ISSUE THREAD

**Issue by jvermill-zz** [Xinyuan-LilyGO/TTGO_TWatch_Library#61]
I'd love to have my watch connect to my phone to display push data, for example caller id on incoming calls.  Don't expect call control, just would like to be able to look at my wrist so I can see if I really need to pick up my phone to deal with the call.

**Comment by lewisxhe** [comment]
This requires the production of mobile phone software, they rely on BLE for data transmission, but there is no such thing here
