### ISSUE TITLE
sketch cannot be uploaded

### ISSUE THREAD

**Issue by rctron** [Xinyuan-LilyGO/TTGO_TWatch_Library#63]
What could be the problem? The watch new,original firmware working.. 
Arduino 1.8.9. (https://dl.espressif.com/dl/package_esp32_index.json) ESP32 driver ok,TTGO T-Watch ok,sketch compile ok.
Upload - then error :
esptool.py v2.6
Connecting........______.....______.....______.....______....._____....._____....._____....._____....._____....._____
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
(on-off button pressing does not help ..)

**Comment by lewisxhe** [comment]
Have you turned on the power, programming is not possible when it is turned off, press and hold the Twatch button for two seconds and release it, and then try to upload again

**Comment by rctron** [comment]
Thanks for the reply.,it didn't help. I get this after pressing a button 2sec : (terminal screen) : 
![Clipboard01](https://user-images.githubusercontent.com/69921365/90805982-b09ead80-e31c-11ea-8502-d35938322d27.jpg)
Any other ideas?

**Comment by lewisxhe** [comment]
This looks like it is already on, can you still not be able to program?

Please try to lower the baud rate, if it still does not work, please contact LilyGo customer service, it looks like an automatic download failure
