### ISSUE TITLE
Error in link

### ISSUE THREAD

**Issue by gosymbian** [Xinyuan-LilyGO/TTGO_TWatch_Library#64]
Hi, 
I try to compile my-ttgo-watch, all compile fine except for the link, I get :

C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x50): undefined reference to `motor_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x54): undefined reference to `display_setup(TTGOClass*)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x58): undefined reference to `screenshot_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x5c): undefined reference to `splash_screen_stage_one(TTGOClass*)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x60): undefined reference to `splash_screen_stage_update(char const*, int)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x64): undefined reference to `powermgm_setup(TTGOClass*)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x68): undefined reference to `gui_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x6c): undefined reference to `weather_app_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x70): undefined reference to `stopwatch_app_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x74): undefined reference to `example_app_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x78): undefined reference to `wifictl_on()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x7c): undefined reference to `splash_screen_stage_finish(TTGOClass*)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x80): undefined reference to `display_get_brightness()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x84): undefined reference to `display_set_brightness(unsigned int)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z5setupv+0x88): undefined reference to `blectl_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z4loopv+0x0): undefined reference to `gui_loop(TTGOClass*)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o:(.literal._Z4loopv+0x4): undefined reference to `powermgm_loop(TTGOClass*)'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o: In function `setup()':
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:51: undefined reference to `motor_setup()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:51: undefined reference to `display_setup(TTGOClass*)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:53: undefined reference to `screenshot_setup()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:56: undefined reference to `splash_screen_stage_one(TTGOClass*)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:58: undefined reference to `splash_screen_stage_update(char const*, int)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:62: undefined reference to `splash_screen_stage_update(char const*, int)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:65: undefined reference to `splash_screen_stage_update(char const*, int)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:66: undefined reference to `splash_screen_stage_update(char const*, int)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:67: undefined reference to `splash_screen_stage_update(char const*, int)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:68: undefined reference to `powermgm_setup(TTGOClass*)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:71: undefined reference to `splash_screen_stage_update(char const*, int)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:72: undefined reference to `gui_setup()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:72: undefined reference to `weather_app_setup()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:74: undefined reference to `stopwatch_app_setup()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:75: undefined reference to `example_app_setup()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:75: undefined reference to `wifictl_on()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:77: undefined reference to `splash_screen_stage_finish(TTGOClass*)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:78: undefined reference to `display_get_brightness()'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:82: undefined reference to `display_set_brightness(unsigned int)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:84: undefined reference to `blectl_setup()'
C:\Users\DOMINI~1\AppData\Local\Temp\arduino_build_534991\sketch\my-ttgo-watch.ino.cpp.o: In function `loop()':
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:100: undefined reference to `gui_loop(TTGOClass*)'
C:\DISK_C\_OneDrive\Arduino\Lilygo\My-TTGO-Watch-master\my-ttgo-watch/my-ttgo-watch.ino:100: undefined reference to `powermgm_loop(TTGOClass*)'
collect2.exe: error: ld returned 1 exit status

can you advice please,
thanks,
Domi.

**Comment by lewisxhe** [comment]
MY-TTGO-WATCH is programmed with platformio ide, not arduino ide
