### ISSUE TITLE
Question about parameters for lv_task_create

### ISSUE THREAD

**Issue by ShotokuTech** [Xinyuan-LilyGO/TTGO_TWatch_Library#65]
Wondering if you could offer a brief description of the parameters associated with these statements. Is '1000' a one second delay for example?:
lv_task_create([](lv_task_t *t) {
}, 1000, LV_TASK_PRIO_MID, nullptr);

I have come to understand this part below, calling the task defined above from void loop(). I just want to understand the definition of lv_task. Thanks.

void loop()
{
    lv_task_handler();
}

**Comment by joshcamas** [comment]
Hey ShotokuTech, love your videos. Anything to do with LVGL should be referenced via the LVGL docs. In your case, I'd check https://docs.lvgl.io/latest/en/html/overview/task.html, in which it references lv_task_create's time to indeed be in ms.

**Comment by ShotokuTech** [comment]
Excellent. Thank you!
