### ISSUE TITLE
No built-in way to stop lvgl

### ISSUE THREAD

**Issue by joshcamas** [Xinyuan-LilyGO/TTGO_TWatch_Library#66]
I'm making a multi-app project, with some apps using lvgl and some using tftespi. There is a nice lvgl_begin function, but nothing related to lvgl_end. There does seem to be a way to stop the ticker (stopLvglTick), but I'm pretty sure that doesn't clear any memory-related stuff.

If possible, adding a way to clear all memory related to lvgl / clearing info related to lvgl would be fantastic!

**Comment by LilyGO** [comment]
There is this description in the LVGL usage specification, execute the following code when it is not needed
https://docs.lvgl.io/master/porting/task-handler.html
