### ISSUE TITLE
Arduino library

### ISSUE THREAD

**Issue by arturo182** [Xinyuan-LilyGO/TTGO_TWatch_Library#7]
Hi, I noticed you copied my Arduino library for the keyboard without any attribution:

https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/840bcaf327b5e7b761b7aa04de6905e655470642/src/keyboard

https://github.com/arturo182/arduino_bbq10kbd/tree/master/src

If possible, please add a note somewhere in the readme, thanks :)

**Comment by lewisxhe** [comment]
Hi arturo182 , I have marked your github link in the source code and examples, thank you for creating this library.

**Comment by arturo182** [comment]
Thanks!
