### ISSUE TITLE
T-Watch 2020:The MISO pin of the TFT screen is 0(GPIO0), or unconnected(NC)?

### ISSUE THREAD

**Issue by happyme531** [Xinyuan-LilyGO/TTGO_TWatch_Library#71]
Well, in the website it shows NULL, but in the code it shows 0.
`#define TWATCH_TFT_MISO             (gpio_num_t)0`
![pic](https://0.rc.xiniu.com/g3/M00/41/01/CgAH6F6mS4GAewwUAASjMb2j3AU249.jpg)

**Comment by lewisxhe** [comment]
The screen does not have MISO, so writing 0 is just to use SPI DMA to drive without being asserted
