### ISSUE TITLE
use FFat error!

### ISSUE THREAD

**Issue by justeene** [Xinyuan-LilyGO/TTGO_TWatch_Library#86]
FFat.format();
用FFat文件系统会报错：
[E][FFat.cpp:35] check_ffat_partition(): No FAT partition found with label ffat
[W][FFat.cpp:94] format(): No partition!

**Comment by lewisxhe** [comment]
你应该是没有选择分区表 ，请看下图 。

![1 (2)](https://user-images.githubusercontent.com/22990954/95714409-c4bab780-0c9a-11eb-86d9-48ca7c41a599.png)

**Comment by justeene** [comment]
> 你应该是没有选择分区表 ，请看下图 。
> 
> ![1 (2)](https://user-images.githubusercontent.com/22990954/95714409-c4bab780-0c9a-11eb-86d9-48ca7c41a599.png)

如果是vscode+platformio怎么配置分区表呢？
我的platformio.ini配置如下：

`
[env:MyWatch]
platform = espressif32
board = ttgo-t-watch
framework = arduino
lib_archive = false
board_build.f_flash = 80000000L
monitor_speed = 115200
monitor_filters =
    default
    esp32_exception_decoder
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -mfix-esp32-psram-cache-issue
src_filter =
    +<*>
`

**Comment by lewisxhe** [comment]
```
board_build.partitions = default_ffat.csv
```

**Comment by justeene** [comment]
问题解决。
我用的是：
board_build.partitions = app3M_fat9M_16MB.csv
![image](https://user-images.githubusercontent.com/6252314/95805088-2c264500-0d37-11eb-84f9-7519d2ba7174.png)
