### ISSUE TITLE
LilyGoGui 

### ISSUE THREAD

**Issue by Neuroplant** [Xinyuan-LilyGO/TTGO_TWatch_Library#89]
example LVGL/LilyGoGui nearly burned my t-Watch 2020.
Watch got realy hot.
Other Prog flashed and Temp got normal

**Comment by lewisxhe** [comment]
But that doesn't have any function, it's just an interface display.

**Comment by Neuroplant** [comment]
That is true, but maybe the task is running wild.
Gruß
Neuroplant
