### ISSUE TITLE
How to program and debug through JTAG

### ISSUE THREAD

**Issue by ivorss** [Xinyuan-LilyGO/TTGO_TWatch_Library#90]
I would like to program and debug the TWatch through the JTAG interface. I can see from the booklet that you expose the following JTAG pins of the ESP32:

IO13 - TCK
IO14 - TMS
IO15 - TDO

However IO12 - TDI is missing. Where on the board can I get it from?

**Comment by lewisxhe** [comment]
TWatch does not support JTAG debugging
