### ISSUE TITLE
Adding a MicroSD card to the TWatch 2020

### ISSUE THREAD

**Issue by RChadwick7** [Xinyuan-LilyGO/TTGO_TWatch_Library#91]
I have checked and found I can make room for an SD card. As the schematic is not available, can you tell me where to solder pins?

**Comment by lewisxhe** [comment]
2020V1 cannot add SD card, only in V2 it is possible to increase, currently under test

**Comment by RChadwick7** [comment]
Why can it not be added? Are the required lines used?
