### ISSUE TITLE
Bug? TTGOClass::touchToSleep() does not disable the touch driver

### ISSUE THREAD

**Issue by SpectralCascade** [Xinyuan-LilyGO/TTGO_TWatch_Library#95]
I expected this mode to disable the touch input driver, but I'm still getting touch interrupts and when I query the touch driver I get valid touch data as though it is not asleep.

**Comment by lewisxhe** [comment]
Sorry, I have been busy lately. Are you using twatch-v1 or twatcg-2109? I will test it

**Comment by SpectralCascade** [comment]
Hiya, I am using ttgo twatch-2020 v1

**Comment by Netspore** [comment]
I also have a ttgo twatch-2020 V1 and would be interested in knowing if there's a way to put the touch sensor into low power mode.  It doesn't appear that the WAKE signal is implemented (or is it)?

**Comment by lewisxhe** [comment]
I have added a test example for the three modes of touch, and the test results are very good. Please note that only TWATCH 2020-V2/2020-V3 has touch wake-up, none of the others support  @Netspore
