### ISSUE TITLE
Osmand Howto

### ISSUE THREAD

**Issue by Neuroplant** [Xinyuan-LilyGO/TTGO_TWatch_Library#97]
Hello,
can you give an short instruction how to connect Osmand to the watch?

thx
Neuroplant

**Comment by Neuroplant** [comment]
found answer
[https://github.com/sharandac/My-TTGO-Watch#bluetooth](https://github.com/sharandac/My-TTGO-Watch#bluetooth)

**Comment by hb9eue** [comment]
Linkd does not seem to point to the right direction anymore. I have the same question :-)

**Comment by hb9eue** [comment]
Ok, answering myself after some more google research and testing.
This is how I got this to work
You need gadgetbridge and osmand+
osmand+ send 'notifications' about directions. Those are passed to the watch by gadgetbridge.
I had to set 'send notification when display on' on gadgetbride.
And you need to move. The first 'direction' from within osmand+, right after clicking on 'navigate' was not being sent, only 'updates'.
